config/routes.rb
Invoice::Application.routes.draw do

  resources :saml

  resources :cb_invoices

  resources :security_roles

  get "invoice/index"
  get "pdf/index"
  get "invoice/show"
  match 'pdf/index/:id' => 'pdf#index'
  post "invoice/get_invoices_by_accountdid"
  post "saml/consume"

     resources :invoice
     resources :pdf

   root :to => 'invoice#index'

  match ':controller/:action/:id'
  match ':controller/:action/:id.:format'
end

app/models/cb_invoice.rb
class CbInvoice < ActiveRecord::Base
  attr_accessible :bill_company_name, :did, :invoice_date, :invoice_number, :status, :total
end

app/controllers/cb_invoices_controller.rb
class CbInvoicesController < ApplicationController
  # GET /cb_invoices
  # GET /cb_invoices.json
  def index
    @cb_invoices = CbInvoice.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cb_invoices }
    end
  end

  # GET /cb_invoices/1
  # GET /cb_invoices/1.json
  def show
    @cb_invoice = CbInvoice.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cb_invoice }
    end
  end

  # GET /cb_invoices/new
  # GET /cb_invoices/new.json
  def new
    @cb_invoice = CbInvoice.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cb_invoice }
    end
  end

  # GET /cb_invoices/1/edit
  def edit
    @cb_invoice = CbInvoice.find(params[:id])
  end

  # POST /cb_invoices
  # POST /cb_invoices.json
  def create
    @cb_invoice = CbInvoice.new(params[:cb_invoice])

    respond_to do |format|
      if @cb_invoice.save
        format.html { redirect_to @cb_invoice, notice: 'Cb invoice was successfully created.' }
        format.json { render json: @cb_invoice, status: :created, location: @cb_invoice }
      else
        format.html { render action: "new" }
        format.json { render json: @cb_invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cb_invoices/1
  # PUT /cb_invoices/1.json
  def update
    @cb_invoice = CbInvoice.find(params[:id])

    respond_to do |format|
      if @cb_invoice.update_attributes(params[:cb_invoice])
        format.html { redirect_to @cb_invoice, notice: 'Cb invoice was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cb_invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cb_invoices/1
  # DELETE /cb_invoices/1.json
  def destroy
    @cb_invoice = CbInvoice.find(params[:id])
    @cb_invoice.destroy

    respond_to do |format|
      format.html { redirect_to cb_invoices_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/cb_invoices_helper.rb
module CbInvoicesHelper
end

app/views/cb_invoices/_form.html.erb
<%= form_for(@cb_invoice) do |f| %>
  <% if @cb_invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cb_invoice.errors.count, "error") %> prohibited this cb_invoice from being saved:</h2>

      <ul>
      <% @cb_invoice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :did %><br />
    <%= f.text_field :did %>
  </div>
  <div class="field">
    <%= f.label :invoice_number %><br />
    <%= f.text_field :invoice_number %>
  </div>
  <div class="field">
    <%= f.label :bill_company_name %><br />
    <%= f.text_field :bill_company_name %>
  </div>
  <div class="field">
    <%= f.label :invoice_date %><br />
    <%= f.date_select :invoice_date %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :total %><br />
    <%= f.text_field :total %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cb_invoices/edit.html.erb
<h1>Editing cb_invoice</h1>

<%= render 'form' %>

<%= link_to 'Show', @cb_invoice %> |
<%= link_to 'Back', cb_invoices_path %>

app/views/cb_invoices/index.html.erb
<h1>Listing cb_invoices</h1>

<table>
  <tr>
    <th>Did</th>
    <th>Invoice number</th>
    <th>Bill company name</th>
    <th>Invoice date</th>
    <th>Status</th>
    <th>Total</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cb_invoices.each do |cb_invoice| %>
  <tr>
    <td><%= cb_invoice.did %></td>
    <td><%= cb_invoice.invoice_number %></td>
    <td><%= cb_invoice.bill_company_name %></td>
    <td><%= cb_invoice.invoice_date %></td>
    <td><%= cb_invoice.status %></td>
    <td><%= cb_invoice.total %></td>
    <td><%= link_to 'Show', cb_invoice %></td>
    <td><%= link_to 'Edit', edit_cb_invoice_path(cb_invoice) %></td>
    <td><%= link_to 'Destroy', cb_invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cb invoice', new_cb_invoice_path %>

app/views/cb_invoices/new.html.erb
<h1>New cb_invoice</h1>

<%= render 'form' %>

<%= link_to 'Back', cb_invoices_path %>

app/views/cb_invoices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Did:</b>
  <%= @cb_invoice.did %>
</p>

<p>
  <b>Invoice number:</b>
  <%= @cb_invoice.invoice_number %>
</p>

<p>
  <b>Bill company name:</b>
  <%= @cb_invoice.bill_company_name %>
</p>

<p>
  <b>Invoice date:</b>
  <%= @cb_invoice.invoice_date %>
</p>

<p>
  <b>Status:</b>
  <%= @cb_invoice.status %>
</p>

<p>
  <b>Total:</b>
  <%= @cb_invoice.total %>
</p>


<%= link_to 'Edit', edit_cb_invoice_path(@cb_invoice) %> |
<%= link_to 'Back', cb_invoices_path %>